# file: test_generated_data.py

import torch
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import os
import warnings

# The only change needed: import the class from your models.py file
from VAE.models.cvae import LSTM_VAE
from config import model_config
# --- CONFIGURATION ---
# (This section remains exactly the same)
MODEL_SAVE_ROUTE = './model_ckpts/'
MODEL_NAME = "model_new_arch"
# ... etc.
# !! IMPORTANT !! These values MUST match the architecture of the saved model.

CHECKPOINT_PATH = os.path.join(MODEL_SAVE_ROUTE, f"{MODEL_NAME}.pth")
NUM_SAMPLES_TO_GENERATE = 1000
OUTLIER_R2_THRESHOLD = 0.90
t_time_array = 65


# --- ANALYSIS FUNCTION ---
# (This function remains exactly the same)
def test_lv_fit(x_data, t):
    """Performs the Lotka-Volterra linear regression test on a single family."""
    N = x_data.shape[1]
    r2_scores = []
    
    for i in range(N):
        x_i_positive = np.maximum(x_data[:, i], 1e-9)
        log_xi = np.log(x_i_positive)
        
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", RuntimeWarning)
            d_log_xi_dt = np.gradient(log_xi, t)

        model = LinearRegression()
        model.fit(x_data, d_log_xi_dt)
        predicted_growth_rate = model.predict(x_data)
        r2 = r2_score(d_log_xi_dt, predicted_growth_rate)
        r2_scores.append(r2)
        
    return np.array(r2_scores)


# --- MAIN EXECUTION SCRIPT ---
# (This section remains exactly the same)
if __name__ == '__main__':
    # --- Step A: Load the trained model ---
    print("--- Loading Neural Network Model ---")
    if not os.path.exists(CHECKPOINT_PATH):
        print(f"FATAL: Model checkpoint not found at {CHECKPOINT_PATH}")
        exit()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    # The code now knows what `LSTM_VAE` is because you imported it.
    model = LSTM_VAE(model_config)
    model.load_state_dict(torch.load(CHECKPOINT_PATH, map_location=device))
    model.to(device)
    model.eval()

    # The rest of the script continues as before...
    # --- Step B: Generate new data from the model ---
    print(f"\n--- Generating {NUM_SAMPLES_TO_GENERATE} new samples from the model ---")
    generated_norm, pred_max_vals = model.generate(NUM_SAMPLES_TO_GENERATE, device)
    generated_data_cube = generated_norm.cpu().numpy()
    generated_max_vals_cube = pred_max_vals.cpu().numpy()
    print("Generation complete.")

    # --- Step C: Run the Lotka-Volterra analysis on the generated data ---
    family_avg_r2_scores = []
    print(f"\n--- Starting LV Analysis on {NUM_SAMPLES_TO_GENERATE} generated families ---")

    for i in range(NUM_SAMPLES_TO_GENERATE):
        if (i + 1) % 100 == 0:
            print(f"  ... processing family {i+1}/{NUM_SAMPLES_TO_GENERATE}")
            
        unscaled_family_data = generated_data_cube[i, :, :]
        max_vals_for_family = generated_max_vals_cube[i, :]
        x_data_rescaled = unscaled_family_data.T * max_vals_for_family
        
        r2_scores_for_family = test_lv_fit(x_data_rescaled, t_time_array)
        family_avg_r2_scores.append(np.mean(r2_scores_for_family))
    
    family_avg_r2_scores = np.array(family_avg_r2_scores)
    print("--- Analysis Complete ---")

    # --- Step D: Report the final summary and visualize the results ---
    print("\n\n--- Overall Quality Report for Data Generated by NN Model ---")
    
    mean_score = np.mean(family_avg_r2_scores)
    median_score = np.median(family_avg_r2_scores)
    min_score = np.min(family_avg_r2_scores)
    outlier_indices = np.where(family_avg_r2_scores < OUTLIER_R2_THRESHOLD)[0]

    print(f"Statistics for Average Family R² Scores (across {len(family_avg_r2_scores)} families):")
    print(f"  - Mean:   {mean_score:.4f}")
    print(f"  - Median: {median_score:.4f}")
    print(f"  - Min:    {min_score:.4f} (Family #{np.argmin(family_avg_r2_scores)})")
    print(f"\nFound {len(outlier_indices)} families with an avg R² < {OUTLIER_R2_THRESHOLD}")

    plt.figure(figsize=(14, 7))
    plt.hist(family_avg_r2_scores, bins=50, edgecolor='black', alpha=0.8)
    plt.axvline(mean_score, color='red', linestyle='--', linewidth=2, label=f'Mean = {mean_score:.3f}')
    plt.axvline(OUTLIER_R2_THRESHOLD, color='orange', linestyle=':', linewidth=3, label=f'Outlier Threshold = {OUTLIER_R2_THRESHOLD}')
    plt.title(f'Distribution of LV-Fit R² Scores for Data Generated by NN Model', fontsize=16)
    plt.xlabel('Average R² Score per Family', fontsize=12)
    plt.ylabel('Number of Families', fontsize=12)
    plt.legend()
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

    worst_family_idx = np.argmin(family_avg_r2_scores)

    unscaled_worst_family = generated_data_cube[worst_family_idx, :, :]
    max_vals_worst_family = generated_max_vals_cube[worst_family_idx, :]
    x_worst_plot = unscaled_worst_family.T * max_vals_worst_family
    worst_score = family_avg_r2_scores[worst_family_idx]

    plt.figure(figsize=(12, 7))
    time = range(65)
    plt.title(f'Time-Series of Worst-Fitting Family #{worst_family_idx} (Avg R² = {worst_score:.3f})', fontsize=16)
    for i in range(7):
        plt.plot(time, x_worst_plot[:, i], label=f'Species {i+1}')
    plt.xlabel('Time', fontsize=12)
    plt.ylabel('Rescaled Abundance', fontsize=12)
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.savefig('./data_checker/worst_family.png')
    plt.show()